name: actualizar-datos

on:
  schedule:
    # Día 1 de cada mes a las 11:15 UTC (≈ 07:15 Chile cuando está en -04)
    - cron: "15 11 1 * *"
  workflow_dispatch: {}   # permitir ejecutarlo manualmente

permissions:
  contents: write   # necesario para commitear data/*.json

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: America/Santiago

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm i

      - name: Run scraper
        run: node js/scrapear.js

      - name: Commit & push if changed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/*.json
            git commit -m "chore(data): actualización automática $(date +'%Y-%m-%d %H:%M %Z')"
            git push
          else
            echo "Sin cambios en data/."
          fi
